name: tastytakeout_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  logger: ^2.0.2+1
  http: ^0.13.3
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.4
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/resources/
    - lib/resources/payment_info/
    - lib/resources/user_image1.png
